{"name": "test_login", "status": "broken", "statusDetails": {"message": "TypeError: 'Logger' object is not callable", "trace": "self = <tests.test_login.TestLogin object at 0x7876761cfcd0>\ninitialize_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9b2ffd78166de81542383cafec9ccc1e\")>\nlogger_creation = <Logger conftest (DEBUG)>\n\n    def test_login(self, initialize_driver,logger_creation):\n      home_page = HomePage(initialize_driver)\n>     log = logger_creation()\nE     TypeError: 'Logger' object is not callable\n\ntests/test_login.py:18: TypeError"}, "start": 1732030149802, "stop": 1732030149803, "uuid": "4d92a352-3527-4f5a-adff-85e048658acc", "historyId": "2116f0ad00ab1de0effc54f114dd9496", "testCaseId": "2116f0ad00ab1de0effc54f114dd9496", "fullName": "tests.test_login.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "aelita-hp-pavilion"}, {"name": "thread", "value": "50528-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}