{"name": "test_login_wrong_credentials", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not callable", "trace": "self = <tests.test_login.TestLogin object at 0x7a598eefba90>\ninitialize_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a93f8ba7f0af2ab6e8417b062768c855\")>\nlogger_creation = None\n\n    def test_login_wrong_credentials(self, initialize_driver,logger_creation):\n      home_page = HomePage(initialize_driver)\n>     logger = logger_creation()\nE     TypeError: 'NoneType' object is not callable\n\ntests/test_login.py:36: TypeError"}, "start": 1732029249350, "stop": 1732029249351, "uuid": "5b90f42a-a709-4b1b-bfe7-48987d84c90c", "historyId": "914ad09e2b30d6d95189061c225a031b", "testCaseId": "914ad09e2b30d6d95189061c225a031b", "fullName": "tests.test_login.TestLogin#test_login_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "aelita-hp-pavilion"}, {"name": "thread", "value": "48191-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}